### ISSUE TITLE
cannot load such file -- obarc (LoadError)

### ISSUE THREAD

**Issue by insanity54** [inertia186/obarc#1]
I'm having some trouble requiring your library. I'm a JavaScript dev so I'm really sorry if this is a code problem on my end. I took a Ruby class one time but I've never used Gemfiles until today so I don't know if I did it right. I was able to use this similar process to require and use a popular gemfile called 'terminal-table', but when applying a similar process to your library I get a load error.

I followed your example as best I could. I created an empty project directory and created a Gemfile--

```
source 'https://rubygems.org'
gem 'obarc', github: 'inertia186/obarc'
```

then I ran `bundler install`--

```
Fetching git://github.com/inertia186/obarc.git
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using unf_ext 0.0.7.2
Using mime-types 2.99.1
Using netrc 0.11.0
Using bundler 1.11.2
Using unf 0.1.4
Using domain_name 0.5.20160310
Using http-cookie 1.0.2
Using rest-client 1.8.0
Using obarc 0.0.1 from git://github.com/inertia186/obarc.git (at master@c98e6c7)
Bundle complete! 1 Gemfile dependency, 9 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

then I created `check.rb`--

```
require 'obarc'
session = OBarc::Session.new(username:'iputmyusernamehere', password: 'iputmypasswordhere')
profile = session.profile
```

then I ran `ruby check.rb` and I get this error--

```
/Users/chrisgrimmett/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- obarc (LoadError)
    from /Users/chrisgrimmett/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from check.rb:1:in `<main>'
```

Did I do something wrong here?

**Comment by inertia186** [comment]
Sorry, I think my notification got routed to spam or something.

Did you ever have any luck with this?  I've never tried it with a bare project.  In that setup, you probably just need to run it with: `ruby -robarc check.rb`

**Comment by inertia186** [comment]
Actually, I just tried it.  This is what `check.rb` should look like:

``` ruby
require 'rubygems'
require 'bundler/setup'

Bundler.require

session = OBarc::Session.new(username:'iputmyusernamehere', password: 'iputmypasswordhere')
profile = session.profile
```

Then:

`ruby check.rb`
